//
// Generated file, do not edit! Created by nedtool 5.5 from CurrentCoordsMessage.msg.
//

#ifndef __CURRENTCOORDSMESSAGE_M_H
#define __CURRENTCOORDSMESSAGE_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0505
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



// cplusplus {{
#include "inet/applications/base/ApplicationPacket_m.h"
// }}

/**
 * Class generated from <tt>CurrentCoordsMessage.msg:21</tt> by nedtool.
 * <pre>
 * packet CurrentCoordsMessage extends ApplicationPacket
 * {
 *     int x;
 *     int y;
 *     int z;
 * }
 * </pre>
 */
class CurrentCoordsMessage : public ::inet::ApplicationPacket
{
  protected:
    int x;
    int y;
    int z;

  private:
    void copy(const CurrentCoordsMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CurrentCoordsMessage&);

  public:
    CurrentCoordsMessage(const char *name=nullptr, short kind=0);
    CurrentCoordsMessage(const CurrentCoordsMessage& other);
    virtual ~CurrentCoordsMessage();
    CurrentCoordsMessage& operator=(const CurrentCoordsMessage& other);
    virtual CurrentCoordsMessage *dup() const override {return new CurrentCoordsMessage(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getX() const;
    virtual void setX(int x);
    virtual int getY() const;
    virtual void setY(int y);
    virtual int getZ() const;
    virtual void setZ(int z);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const CurrentCoordsMessage& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, CurrentCoordsMessage& obj) {obj.parsimUnpack(b);}


#endif // ifndef __CURRENTCOORDSMESSAGE_M_H

